import Navigation from './components/Navigation';
import Footer from './components/Footer';
import './font.css'; 
import './scroll.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&family=Noto+Serif:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Navigation />
        <main>
          {children}
        </main>
        <Footer />      
      </body>
    </html>
  );
}
