import Navigation from './components/Navigation';
import Footer from './components/Footer'; // Footer 컴포넌트 임포트

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <main>
          {children}
        </main>
        <Footer />      
      </body>
    </html>
  );
}
